import { notFound } from 'next/navigation';
import ToolCase from './tool-case';

const cases = {
  campaign:{kicker:'母婴护理 · 小红书内容孵化',title:'Ms. Chu',period:'2025.07 — 2026.07',tone:'amber',summary:'围绕真实护理经验建立内容方向，联动香港及内地达人，让专业信息以更可信、更生活化的方式被用户看见。',stats:[['220万+','总曝光'],['33万+','总阅读'],['3.3万+','总互动'],['100+','达人合作']],bullets:[['达人合作推广','围绕品牌目标人群与产品定位，筛选与 Ms. Chu 品牌调性高度适配的母婴、敏感肌等垂类达人，以付费合作为核心，推动达人从真实使用体验出发，产出产品实测内容及高质量视觉素材。针对首轮合作达人进行二次筛选，结合内容质量、达人匹配度及合作表现，筛选优质达人推进深度视频合作，持续沉淀高质量达人资源与内容资产。'],['痛点内容策划','结合 Ms. Chu 品牌调性、目标用户痛点及产品核心卖点，持续优化内容侧重与传播方向。围绕「湿疹护理三件套」「天然有机」等核心卖点，重点策划使用前后效果对比、宝妈真实体验、敏感肌护理场景等内容，并结合季节变化、节日节点及日常使用场景规划多元化创意主题，提升内容的真实感、场景感与用户共鸣。'],['项目复盘','持续跟踪内容质量、互动反馈与达人表现，为后续合作筛选和内容方向提供依据。']]},
  global:{kicker:'香港古着 · 小红书内容推广',title:'美之时装',period:'2025.09 — 2026.06',tone:'green',summary:'围绕中古服装与高性价比特色，通过生活方式、时尚穿搭达人合作及优质内容投流，持续提升品牌曝光与用户种草效率。',stats:[['OOTD','核心内容'],['付费＋投流','合作模式'],['香港','本地场景'],['持续','创意输出']],bullets:[['达人合作推广','筛选生活方式、时尚穿搭类达人，以付费合作与优质内容投流强化品牌曝光。'],['创意内容输出','围绕 OOTD、中古单品搭配与低价淘好物，持续策划多元创意主题。']]},
  lifestyle:{kicker:'经典重塑 · 香港年轻化传播',title:'Esprit',period:'品牌内容焕新',tone:'blue',summary:'围绕「Rewrite the Classic」理念，将品牌历史、香港城市记忆与 Gen Z 生活方式重新连接，建立年轻化、本地化的新媒体内容体系。',stats:[['3大','内容模块'],['双平台','内容矩阵'],['香港','本地叙事'],['KOL/KOC','精准合作']],bullets:[['品牌内容构建','梳理品牌历史与核心价值，建立年轻化、本地化的内容定位。'],['品牌新媒体矩阵','规划 Instagram 与小红书的差异化内容及互动共创机制。'],['品牌内容投放','以阶段性传播链路和精准达人合作推动品牌认知与种草。']]},
  product:{kicker:'运营提效 · AI 工作流',title:'博主接单平台与邀约工具',period:'2026.03 — 2026.07',tone:'blue',summary:'把高频重复的达人沟通流程产品化，参与需求分析、流程测试与功能迭代，形成可复用的运营闭环。',stats:[['1000+','达人资源池'],['5大','主流平台'],['AARRR','分层模型'],['闭环','试用与迭代']],bullets:[['流程产品化','将筛选、确认合作、内容审核和发布沉淀为标准化运营 SOP。'],['用户分层','围绕获客、激活、留存、变现和传播，设计达人生命周期运营。'],['反馈迭代','通过真实试用定位问题，推动登录跳转等关键体验修复。']]}
} as const;

export default async function CasePage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  if(id==='product') return <ToolCase/>;
  const item=cases[id as keyof typeof cases];
  if(!item) notFound();
  return <main className={`casePage paper ${item.tone}`}><div className="grain"/>
    <a className="caseClose" href="/#work" aria-label="返回过往经历">×</a>
    <section className={`casePageHero ${id==='lifestyle'?'espritHero':''}`}><div className="caseIntro"><span className="eyebrow">{item.kicker}</span><h1>{item.title}</h1><p className="casePeriod">{item.period}</p><p className="caseSummary">{item.summary}</p><div className="caseChips"><span>CASE STUDY</span><span>内容策略</span><span>项目复盘</span></div></div>{id==='campaign'?<div className="campaignBrief"><article><span>01</span><h2>达人合作推广</h2><p>围绕品牌目标人群与产品定位，筛选与 <strong>Ms. Chu 品牌调性高度适配的母婴、敏感肌等垂类达人</strong>，以付费合作为核心，推动达人从真实使用体验出发，产出产品实测内容及高质量视觉素材。针对首轮合作达人进行二次筛选，结合内容质量、达人匹配度及合作表现，筛选优质达人推进深度视频合作，持续沉淀高质量达人资源与内容资产。</p></article><article><span>02</span><h2>痛点内容策划</h2><p>结合 <strong>Ms. Chu 品牌调性、目标用户痛点及产品核心卖点</strong>，持续优化内容侧重与传播方向。围绕「湿疹护理三件套」「天然有机」等核心卖点，重点策划<strong>使用前后效果对比、宝妈真实体验、敏感肌护理场景</strong>等内容，并结合季节变化、节日节点及日常使用场景规划多元化创意主题，提升内容的真实感、场景感与用户共鸣。</p></article></div>:id==='global'?<div className="campaignBrief"><article><span>01</span><h2>达人合作推广</h2><p>筛选与品牌调性及目标客群高度适配的<strong>生活方式、时尚穿搭类达人</strong>，采用「付费合作 + 优质内容投流」的核心合作模式。内容以 <strong>OOTD 穿搭展示</strong>为核心，通过巧思搭配、真实生活化表达及戏剧冲突等内容形式，强化中古服装的视觉表现力与内容吸引力，提升品牌曝光与用户种草效率。</p></article><article><span>02</span><h2>创意内容输出</h2><p>结合<strong>美之时装品牌调性与「中古服装、高性价比」核心卖点</strong>，紧跟平台热点与用户内容偏好，以打造高传播潜力内容为目标。重点围绕 <strong>OOTD、中古单品搭配、低价淘好物</strong>等方向进行内容策划，并结合季节趋势、节日节点及重大活动延展多元创意主题，持续丰富品牌内容场景与传播话题。</p></article></div>:id==='lifestyle'?<div className="espritBrief"><article><span>01</span><h2>品牌内容构建</h2><h3>品牌历史与核心价值梳理</h3><p>从 80、90 年代的潮流记忆到品牌重新回归香港，提炼「经典重塑 × 年轻焕新」的核心传播价值，将品牌历史资产转化为具有当代传播力的品牌故事。</p><h3>品牌年轻化内容定位</h3><p>围绕 Esprit「Rewrite the Classic」理念，以「不是回到过去，而是让经典重新属于现在」为内容主线，在保留品牌复古、自由与活力基因的同时，引入 Gen Z 穿搭、香港城市生活及年轻文化语境，重新建立品牌与新一代消费者的连接。</p><h3>香港本地化内容策划</h3><p>结合 Esprit 与香港的历史渊源及铜锣湾旗舰店场景，将品牌内容融入香港街头、Citywalk、OOTD 等本地生活方式，策划「Esprit Back to Hong Kong」「两代人的 Esprit」「经典重新穿」等主题，强化品牌回归的城市记忆与话题性。</p></article><article><span>02</span><h2>品牌新媒体矩阵</h2><h3>社交媒体内容矩阵搭建</h3><p>围绕 Instagram、小红书等核心平台规划差异化内容：Instagram 聚焦品牌视觉、Campaign 与新品形象，小红书强化穿搭种草、门店探店及真实消费体验，通过统一视觉与差异化内容建立完整的新媒体传播矩阵。</p><h3>热点洞察与创意内容生产</h3><p>围绕复古回潮、OOTD、Citywalk、港风等内容趋势快速延展选题，并结合新品、季节、节日及重大活动持续输出年轻化创意内容。</p><h3>用户互动与品牌共创</h3><p>围绕「你记忆中的 Esprit」「经典单品重新穿」等话题设计互动机制，通过评论互动、UGC 征集及两代消费者共创，连接品牌老用户与年轻消费者，将品牌记忆进一步沉淀为社交内容资产。</p></article><article><span>03</span><h2>品牌内容投放</h2><h3>阶段性内容投放策略</h3><p>围绕「品牌回归声量 → 门店种草 → 产品穿搭 → 用户口碑」规划内容传播链路，结合品牌回归、新店、新品及营销节点进行阶段性投放，实现从品牌认知到消费兴趣的持续转化。</p><h3>KOL/KOC 精准合作</h3><p>筛选与品牌调性匹配的时尚穿搭、香港生活方式、复古潮流等垂类达人，通过「付费合作 + 优质内容投流」扩大传播，以探店、OOTD、街拍及短视频等形式强化 Esprit 的年轻化品牌形象与产品穿搭价值。</p><h3>两代消费者 × 内容共创</h3><p>利用 Esprit 跨世代的品牌认知优势，以「90s × Gen Z」「旧款 × 新款」「母女/父子穿搭」等创意制造代际反差，将消费者的品牌记忆与当代穿搭方式结合，让经典品牌资产转化为具有社交传播潜力的内容。</p></article></div>:<div className="modalCollage"><div className="caseImage a">CASE<br/>STUDY</div><div className="caseImage b">SOCIAL<br/>CONTENT</div><div className="caseImage c">RESULTS<br/>↗</div></div>}</section>
    <section className="casePageStats">{item.stats.map(s=><div key={s[1]}><strong>{s[0]}</strong><span>{s[1]}</span></div>)}</section>
    {id!=='campaign'&&id!=='global'&&id!=='lifestyle'&&<section className="caseMethods"><div className="methodTitle"><span className="eyebrow">WHAT I DID</span><h2>项目方法拆解</h2><p>从策略到落地，每一步都对应可验证的运营结果。</p></div><div className="detailGrid">{item.bullets.map((b,i)=><article key={b[0]}><span>0{i+1}</span><h3>{b[0]}</h3><p>{b[1]}</p></article>)}</div></section>}
    <section className="caseGallery"><span className="eyebrow">SELECTED VISUALS</span><h2>案例图片</h2>{id==='campaign'?<div className="realCaseGallery"><figure><img src="/cases/mschu-01.jpg" alt="Ms. Chu 小红书达人合作案例一"/><figcaption>母婴垂类达人 · 产品实测内容</figcaption></figure><figure><img src="/cases/mschu-02.jpg" alt="Ms. Chu 小红书达人合作案例二"/><figcaption>真实使用体验 · 敏感肌护理场景</figcaption></figure><figure><img src="/cases/mschu-03.jpg" alt="Ms. Chu 小红书达人合作案例三"/><figcaption>湿疹护理主题 · 深度内容合作</figcaption></figure></div>:id==='global'?<div className="realCaseGallery fashionGallery"><figure><img src="/cases/meizhi-01.jpg" alt="美之时装小红书达人合作案例一"/><figcaption>香港古着探店 · OOTD 穿搭展示</figcaption></figure><figure><img src="/cases/meizhi-02.jpg" alt="美之时装小红书达人合作案例二"/><figcaption>生活方式达人 · 低价淘好物</figcaption></figure><figure><img src="/cases/meizhi-03.jpg" alt="美之时装小红书达人合作案例三"/><figcaption>中古单品搭配 · 热点内容策划</figcaption></figure></div>:id==='lifestyle'?<div className="realCaseGallery fashionGallery"><figure><img src="/cases/esprit-01.jpg" alt="Esprit 小红书达人合作案例一"/><figcaption>品牌回归 · 香港潮流记忆</figcaption></figure><figure><img src="/cases/esprit-02.jpg" alt="Esprit 小红书达人合作案例二"/><figcaption>铜锣湾探店 · 年轻化穿搭</figcaption></figure><figure><img src="/cases/esprit-03.jpg" alt="Esprit 小红书达人合作案例三"/><figcaption>本地生活方式 · 门店种草</figcaption></figure></div>:<div className="imagePlaceholder"><div>CASE VISUAL 01</div><div>CASE VISUAL 02</div><div>CASE VISUAL 03</div><p>这里将替换为真实项目截图、笔记封面与数据复盘图片</p></div>}</section>
    <footer className="caseFooter"><a href="/#work">← 返回所有品牌</a><a href="mailto:ryanliu200212@gmail.com">联系我 ↗</a></footer>
  </main>
}
